@server = https://turbo-space-succotash-ggww4w94wj6fppx7-8080.app.github.dev/
@employees = {{server}}/api/employees
###
GET {{employees}}
###
POST {{employees}}
Content-Type: application/json

{
  "firstName" : "Bilbo",
  "lastName" : "Baggins",
  "description" : "burglar"
}